# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.   # noqa: E501

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import opendota_client
from opendota_client.api.request_api import RequestApi  # noqa: E501
from opendota_client.rest import ApiException


class TestRequestApi(unittest.TestCase):
    """RequestApi unit test stubs"""

    def setUp(self):
        self.api = opendota_client.api.request_api.RequestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_request_job_id_get(self):
        """Test case for request_job_id_get

        GET /request/{jobId}  # noqa: E501
        """
        pass

    def test_request_match_id_post(self):
        """Test case for request_match_id_post

        POST /request/{match_id}  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
