# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.   # noqa: E501

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20027(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_game_items': 'InlineResponse20027StartGameItems',
        'early_game_items': 'InlineResponse20027EarlyGameItems',
        'mid_game_items': 'InlineResponse20027MidGameItems',
        'late_game_items': 'InlineResponse20027LateGameItems'
    }

    attribute_map = {
        'start_game_items': 'start_game_items',
        'early_game_items': 'early_game_items',
        'mid_game_items': 'mid_game_items',
        'late_game_items': 'late_game_items'
    }

    def __init__(self, start_game_items=None, early_game_items=None, mid_game_items=None, late_game_items=None):  # noqa: E501
        """InlineResponse20027 - a model defined in Swagger"""  # noqa: E501

        self._start_game_items = None
        self._early_game_items = None
        self._mid_game_items = None
        self._late_game_items = None
        self.discriminator = None

        if start_game_items is not None:
            self.start_game_items = start_game_items
        if early_game_items is not None:
            self.early_game_items = early_game_items
        if mid_game_items is not None:
            self.mid_game_items = mid_game_items
        if late_game_items is not None:
            self.late_game_items = late_game_items

    @property
    def start_game_items(self):
        """Gets the start_game_items of this InlineResponse20027.  # noqa: E501


        :return: The start_game_items of this InlineResponse20027.  # noqa: E501
        :rtype: InlineResponse20027StartGameItems
        """
        return self._start_game_items

    @start_game_items.setter
    def start_game_items(self, start_game_items):
        """Sets the start_game_items of this InlineResponse20027.


        :param start_game_items: The start_game_items of this InlineResponse20027.  # noqa: E501
        :type: InlineResponse20027StartGameItems
        """

        self._start_game_items = start_game_items

    @property
    def early_game_items(self):
        """Gets the early_game_items of this InlineResponse20027.  # noqa: E501


        :return: The early_game_items of this InlineResponse20027.  # noqa: E501
        :rtype: InlineResponse20027EarlyGameItems
        """
        return self._early_game_items

    @early_game_items.setter
    def early_game_items(self, early_game_items):
        """Sets the early_game_items of this InlineResponse20027.


        :param early_game_items: The early_game_items of this InlineResponse20027.  # noqa: E501
        :type: InlineResponse20027EarlyGameItems
        """

        self._early_game_items = early_game_items

    @property
    def mid_game_items(self):
        """Gets the mid_game_items of this InlineResponse20027.  # noqa: E501


        :return: The mid_game_items of this InlineResponse20027.  # noqa: E501
        :rtype: InlineResponse20027MidGameItems
        """
        return self._mid_game_items

    @mid_game_items.setter
    def mid_game_items(self, mid_game_items):
        """Sets the mid_game_items of this InlineResponse20027.


        :param mid_game_items: The mid_game_items of this InlineResponse20027.  # noqa: E501
        :type: InlineResponse20027MidGameItems
        """

        self._mid_game_items = mid_game_items

    @property
    def late_game_items(self):
        """Gets the late_game_items of this InlineResponse20027.  # noqa: E501


        :return: The late_game_items of this InlineResponse20027.  # noqa: E501
        :rtype: InlineResponse20027LateGameItems
        """
        return self._late_game_items

    @late_game_items.setter
    def late_game_items(self, late_game_items):
        """Sets the late_game_items of this InlineResponse20027.


        :param late_game_items: The late_game_items of this InlineResponse20027.  # noqa: E501
        :type: InlineResponse20027LateGameItems
        """

        self._late_game_items = late_game_items

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20027, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20027):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
