# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.   # noqa: E501

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2009(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'field': 'str',
        'n': 'int',
        'sum': 'int'
    }

    attribute_map = {
        'field': 'field',
        'n': 'n',
        'sum': 'sum'
    }

    def __init__(self, field=None, n=None, sum=None):  # noqa: E501
        """InlineResponse2009 - a model defined in Swagger"""  # noqa: E501

        self._field = None
        self._n = None
        self._sum = None
        self.discriminator = None

        if field is not None:
            self.field = field
        if n is not None:
            self.n = n
        if sum is not None:
            self.sum = sum

    @property
    def field(self):
        """Gets the field of this InlineResponse2009.  # noqa: E501

        field  # noqa: E501

        :return: The field of this InlineResponse2009.  # noqa: E501
        :rtype: str
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this InlineResponse2009.

        field  # noqa: E501

        :param field: The field of this InlineResponse2009.  # noqa: E501
        :type: str
        """

        self._field = field

    @property
    def n(self):
        """Gets the n of this InlineResponse2009.  # noqa: E501

        number  # noqa: E501

        :return: The n of this InlineResponse2009.  # noqa: E501
        :rtype: int
        """
        return self._n

    @n.setter
    def n(self, n):
        """Sets the n of this InlineResponse2009.

        number  # noqa: E501

        :param n: The n of this InlineResponse2009.  # noqa: E501
        :type: int
        """

        self._n = n

    @property
    def sum(self):
        """Gets the sum of this InlineResponse2009.  # noqa: E501

        sum  # noqa: E501

        :return: The sum of this InlineResponse2009.  # noqa: E501
        :rtype: int
        """
        return self._sum

    @sum.setter
    def sum(self, sum):
        """Sets the sum of this InlineResponse2009.

        sum  # noqa: E501

        :param sum: The sum of this InlineResponse2009.  # noqa: E501
        :type: int
        """

        self._sum = sum

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2009, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2009):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
