# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.   # noqa: E501

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse2002MmrEstimate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'estimate': 'float',
        'std_dev': 'float',
        'n': 'int'
    }

    attribute_map = {
        'estimate': 'estimate',
        'std_dev': 'stdDev',
        'n': 'n'
    }

    def __init__(self, estimate=None, std_dev=None, n=None):  # noqa: E501
        """InlineResponse2002MmrEstimate - a model defined in Swagger"""  # noqa: E501

        self._estimate = None
        self._std_dev = None
        self._n = None
        self.discriminator = None

        if estimate is not None:
            self.estimate = estimate
        if std_dev is not None:
            self.std_dev = std_dev
        if n is not None:
            self.n = n

    @property
    def estimate(self):
        """Gets the estimate of this InlineResponse2002MmrEstimate.  # noqa: E501

        estimate  # noqa: E501

        :return: The estimate of this InlineResponse2002MmrEstimate.  # noqa: E501
        :rtype: float
        """
        return self._estimate

    @estimate.setter
    def estimate(self, estimate):
        """Sets the estimate of this InlineResponse2002MmrEstimate.

        estimate  # noqa: E501

        :param estimate: The estimate of this InlineResponse2002MmrEstimate.  # noqa: E501
        :type: float
        """

        self._estimate = estimate

    @property
    def std_dev(self):
        """Gets the std_dev of this InlineResponse2002MmrEstimate.  # noqa: E501

        stdDev  # noqa: E501

        :return: The std_dev of this InlineResponse2002MmrEstimate.  # noqa: E501
        :rtype: float
        """
        return self._std_dev

    @std_dev.setter
    def std_dev(self, std_dev):
        """Sets the std_dev of this InlineResponse2002MmrEstimate.

        stdDev  # noqa: E501

        :param std_dev: The std_dev of this InlineResponse2002MmrEstimate.  # noqa: E501
        :type: float
        """

        self._std_dev = std_dev

    @property
    def n(self):
        """Gets the n of this InlineResponse2002MmrEstimate.  # noqa: E501

        n  # noqa: E501

        :return: The n of this InlineResponse2002MmrEstimate.  # noqa: E501
        :rtype: int
        """
        return self._n

    @n.setter
    def n(self, n):
        """Sets the n of this InlineResponse2002MmrEstimate.

        n  # noqa: E501

        :param n: The n of this InlineResponse2002MmrEstimate.  # noqa: E501
        :type: int
        """

        self._n = n

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2002MmrEstimate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2002MmrEstimate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
