# coding: utf-8

"""
    OpenDota API

    # Introduction The OpenDota API provides Dota 2 related data including advanced match data extracted from match replays.  You can find data that can be used to convert hero and ability IDs and other information provided by the API from the [dotaconstants](https://github.com/odota/dotaconstants) repository.  **Beginning 2018-04-22, the OpenDota API is limited to 50,000 free calls per month and 60 requests/minute** We offer a Premium Tier with unlimited API calls and higher rate limits. Check out the [API page](https://www.opendota.com/api-keys) to learn more.   # noqa: E501

    OpenAPI spec version: 18.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from opendota_client.api_client import ApiClient


class HeroesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def heroes_get(self, **kwargs):  # noqa: E501
        """GET /heroes  # noqa: E501

        Get hero data  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_get(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[InlineResponse20023]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heroes_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.heroes_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def heroes_get_with_http_info(self, **kwargs):  # noqa: E501
        """GET /heroes  # noqa: E501

        Get hero data  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_get_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :return: list[InlineResponse20023]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heroes', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[InlineResponse20023]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heroes_hero_id_durations_get(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/durations  # noqa: E501

        Get hero performance over a range of match durations  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_durations_get(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse20026]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heroes_hero_id_durations_get_with_http_info(hero_id, **kwargs)  # noqa: E501
        else:
            (data) = self.heroes_hero_id_durations_get_with_http_info(hero_id, **kwargs)  # noqa: E501
            return data

    def heroes_hero_id_durations_get_with_http_info(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/durations  # noqa: E501

        Get hero performance over a range of match durations  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_durations_get_with_http_info(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse20026]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_durations_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params or
                params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_durations_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heroes/{hero_id}/durations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[InlineResponse20026]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heroes_hero_id_item_popularity_get(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/itemPopularity  # noqa: E501

        Get item popularity of hero categoried by start, early, mid and late game, analyzed from professional games  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_item_popularity_get(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: InlineResponse20027
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heroes_hero_id_item_popularity_get_with_http_info(hero_id, **kwargs)  # noqa: E501
        else:
            (data) = self.heroes_hero_id_item_popularity_get_with_http_info(hero_id, **kwargs)  # noqa: E501
            return data

    def heroes_hero_id_item_popularity_get_with_http_info(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/itemPopularity  # noqa: E501

        Get item popularity of hero categoried by start, early, mid and late game, analyzed from professional games  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_item_popularity_get_with_http_info(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: InlineResponse20027
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_item_popularity_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params or
                params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_item_popularity_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heroes/{hero_id}/itemPopularity', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20027',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heroes_hero_id_matches_get(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/matches  # noqa: E501

        Get recent matches with a hero  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_matches_get(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse20015]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heroes_hero_id_matches_get_with_http_info(hero_id, **kwargs)  # noqa: E501
        else:
            (data) = self.heroes_hero_id_matches_get_with_http_info(hero_id, **kwargs)  # noqa: E501
            return data

    def heroes_hero_id_matches_get_with_http_info(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/matches  # noqa: E501

        Get recent matches with a hero  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_matches_get_with_http_info(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse20015]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_matches_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params or
                params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_matches_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heroes/{hero_id}/matches', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[InlineResponse20015]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heroes_hero_id_matchups_get(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/matchups  # noqa: E501

        Get results against other heroes for a hero  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_matchups_get(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse20025]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heroes_hero_id_matchups_get_with_http_info(hero_id, **kwargs)  # noqa: E501
        else:
            (data) = self.heroes_hero_id_matchups_get_with_http_info(hero_id, **kwargs)  # noqa: E501
            return data

    def heroes_hero_id_matchups_get_with_http_info(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/matchups  # noqa: E501

        Get results against other heroes for a hero  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_matchups_get_with_http_info(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[InlineResponse20025]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_matchups_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params or
                params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_matchups_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heroes/{hero_id}/matchups', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[InlineResponse20025]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def heroes_hero_id_players_get(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/players  # noqa: E501

        Get players who have played this hero  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_players_get(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[list[object]]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.heroes_hero_id_players_get_with_http_info(hero_id, **kwargs)  # noqa: E501
        else:
            (data) = self.heroes_hero_id_players_get_with_http_info(hero_id, **kwargs)  # noqa: E501
            return data

    def heroes_hero_id_players_get_with_http_info(self, hero_id, **kwargs):  # noqa: E501
        """GET /heroes/{hero_id}/players  # noqa: E501

        Get players who have played this hero  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.heroes_hero_id_players_get_with_http_info(hero_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param int hero_id: Hero ID (required)
        :return: list[list[object]]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['hero_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method heroes_hero_id_players_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'hero_id' is set
        if ('hero_id' not in params or
                params['hero_id'] is None):
            raise ValueError("Missing the required parameter `hero_id` when calling `heroes_hero_id_players_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'hero_id' in params:
            path_params['hero_id'] = params['hero_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/heroes/{hero_id}/players', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[list[object]]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
